
------------------------------------------------
['бт jhe']
Traceback (most recent call last):
  File "C:/Users/Dakelnut/Dropbox/Моё/Проекты/Программы Python/vk_bot/complete_bot/vk_bot_2.0/new_timetable.py", line 79, in main_method
    answer = understand_message.understand_meaning(el,self.name_of_bd)
  File "C:\Users\Dakelnut\Dropbox\Моё\Проекты\Программы Python\vk_bot\complete_bot\vk_bot_2.0\understand_message.py", line 60, in understand_meaning
    raise e
  File "C:\Users\Dakelnut\Dropbox\Моё\Проекты\Программы Python\vk_bot\complete_bot\vk_bot_2.0\understand_message.py", line 57, in understand_meaning
    result = sup.get_key(dict, max(dict.values()))
ValueError: max() arg is an empty sequence

------------------------------------------------
{50336045: 'бт где пары'}
Traceback (most recent call last):
  File "C:/Users/Dakelnut/Dropbox/Моё/Проекты/Программы Python/vk_bot/complete_bot/vk_bot_2.0/new_timetable.py", line 82, in main_method
    self.api.messages.send(oauth='1', v='5.45', user_id=author, message=answer)
  File "C:\Users\Dakelnut\AppData\Local\Programs\Python\Python35-32\lib\site-packages\vk_requests\api.py", line 64, in __call__
    return self._api.make_request(request_obj=self)
  File "C:\Users\Dakelnut\AppData\Local\Programs\Python\Python35-32\lib\site-packages\vk_requests\api.py", line 36, in make_request
    return self._session.make_request(request_obj)
  File "C:\Users\Dakelnut\AppData\Local\Programs\Python\Python35-32\lib\site-packages\vk_requests\auth.py", line 446, in make_request
    raise vk_error
vk_requests.exceptions.VkAPIError: error_code=100,message='One of the parameters specified was missing or invalid: message is empty or invalid',request_params={'oauth': '1', 'user_id': '50336045', 'v': '5.45', 'message': '', 'method': 'messages.send'}

